trigger: none

variables:
  acrServiceConnection: 'AcrServiceConnection'
  dockerImageName: 'app-demo'
  dockerfilePath: 'Dockerfile'
pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build_Java
    displayName: "Compilar proyecto Java"
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.7'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        goals: 'package'
