version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - mvn --version
  pre_build:
    commands:
      - echo "Cleaning and installing..."
      - mvn clean