version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
  parameter-store:
    AWS_ACCOUNT_ID: "MY_ACCOUNT_ID"

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_REPO_NAME=test/devops
      - ECR_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "Tag image with tag $IMAGE_TAG"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_URI:latest .
      - echo "Tagging Docker image..."
      - docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:latest
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Saving image variable..."
      - echo "[{\"name\":\"app\",\"imageUri\":\"$ECR_REPO_URI:$IMAGE_TAG\"}]" > imageDetail.json
      - cat imageDetail.json
artifacts:
  files: imageDetail.json
